brotli2-sys CVE-2020-8927
rustsec/advisory-db pull request #1124
Opened 2021-12-20 20:52 UTC by insanitybit

Hey, haven't submitted anything before. Brotli reported CVE-2020-8927. The brotli-sys crate is appears to link to a vulnerable version. I'm unsure if the brotli2 crate itself is vulnerable, but I think so based on the following:

https://docs.rs/brotli2/latest/src/brotli2/raw.rs.html#180-195

I also didn't see any limits imposed on the streaming reader/writer that would prevent those interfaces from being vulnerable.

2021-12-20 20:59 UTC, Shnatsel requested changes
Thank you for the report!

CI failed because the file format is not just TOML, it's Markdown with embedded TOML content - you can use [this](https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/openssl-src/RUSTSEC-2021-0129.md) as a template.

It would also be nice to include a description of the vulnerability. Copy-pasting from the CVE would be sufficient.

2021-12-20 20:59 UTC, Shnatsel commented on crates/brotli2-sys/RUSTSEC-0000-0000.md
> +related = ["CVE-2020-8927"]
```suggestion
aliases = ["CVE-2020-8927"]
```

2021-12-20 20:59 UTC, tarcieri commented
Have a look at an example advisory for the format. It's Markdown with TOML "front matter":

https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/openssl-src/RUSTSEC-2021-0057.md

2021-12-20 20:59 UTC, Shnatsel commented
Also, please report the issue to the brotli-rs issue tracker if you haven't already.

2021-12-20 21:03 UTC, Shnatsel commented
Since no fix is available, perhaps we should mention that the pure-Rust [`brotli`](https://crates.io/crates/brotli) crate is not affected, and is a valid although higher-effort mitigation path? @tarcieri what do you think?

2021-12-20 21:04 UTC, tarcieri commented
Sounds good to me

2021-12-20 21:17 UTC, insanitybit commented
Thanks for the quick response and feedback. I've pushed up a revision that should match your requests, and I've also created in issue in the brotli2-rs repository https://github.com/bitemyapp/brotli2-rs/issues/45.

2021-12-20 21:32 UTC, colin-grapl commented
From what I can tell it may be fairly straightforward to migrate to the `brotli` crate for code currently using `brotli2`. 

For example,

`brotli2::read::BrotliDecoder` and `brotli::reader::Decompressor` have very similar APIs.

* Decompressor implements all non-trait api compatible methods (as well as a dictionary method)
* Decompressor implements Read

It even appears that the `brotli` crate exports a C API (`brotli::ffi`) that's compatible, so one could potentially just swap out the packaged `brotli` for the crate.

2021-12-20 21:45 UTC, jorgecarleitao commented
I would refrain from making recommendations about using other crates here - imo that is a discussion for reddit, forums, etc. Imo the scope here is to disclose the vulnerability, which code branches hits it, and how to mitigate it within the dependency taken (e.g. avoid using function X with parameters Y).

2021-12-20 22:59 UTC, Shnatsel requested changes

2021-12-20 22:59 UTC, Shnatsel commented on crates/brotli2-sys/RUSTSEC-0000-0000.md
> +# There isn't a patch for brotli2-sys, but version 1.0.9 of google/brotli is patched
I understand version 1.0.8 is also patched?

2021-12-20 22:59 UTC, Shnatsel commented on crates/brotli2-sys/RUSTSEC-0000-0000.md
> +If one cannot update, we recommend to use the "streaming" API as opposed to the "one-shot" API, and impose chunk size limits.
I understand the issue with the brotli-rs package specifically is that it bundles an old version of the C implementation of Brotli? Perhaps this should be explicitly called out?

2021-12-20 22:59 UTC, Shnatsel commented on crates/brotli2-sys/RUSTSEC-0000-0000.md
> +package = "brotli2-sys"
CI complains that there is no package `brotli2-sys` on crates.io; I assume you meant `brotli-sys`?

2021-12-20 23:03 UTC, tarcieri commented
> I would refrain from making recommendations about using other crates here

@jorgecarleitao we frequently provide curated advice about alternatives, although typically for abandoned crates as opposed to the context of a security vulnerability

> imo that is a discussion for reddit, forums, etc.

My personal opinion: that's a terrible antipattern. Far too often people reach for the first recommendation they see in the context of a reddit/forum thread, but those media can't provide curated advice. This results in outdated, unreviewed advice becoming standard practice just because it happens to be the top hit on Google et al for a particular search term.

With an advisory we can provide up-to-date advice which evolves along with the crate ecosystem, rather than one person's dated opinion.

2021-12-21 17:52 UTC, Shnatsel commented
I wanted to get this merged quickly, but this PR does not allow edits by maintainers, so I've created a new PR: #1127.

2021-12-21 20:51 UTC, Shnatsel commented
I went ahead and merged #1127 not to delay the notification to users any longer. I'm open to amendments in case I missed something.

Thanks again for reporting the issue!

2021-12-21 20:51 UTC, closed without merging

2021-12-21 21:03 UTC, insanitybit commented
Awesome, thanks for taking care of that.