Undefined behavior in `dashmap`
rustsec/advisory-db pull request #1146
Opened 2022-01-10 09:01 UTC by baptiste0928

Undefined behavior may occur when using the `Ref::value` of `dashmap`. See https://github.com/xacrimon/dashmap/issues/167 for more information.

Example vulnerable code:
```rust
use dashmap::DashMap;

fn main() {
    let x = DashMap::new();

    x.insert(1, 1);

    let borrow = x.get(&1).unwrap();
    let val = borrow.value();
    std::mem::drop(borrow);
    let mut borrow_mut = x.get_mut(&1).unwrap();
    let val_mut = borrow_mut.value_mut(); // non-exclusive mutable reference!!!
    println!("{}", val);
}
```

I'm unsure about in which categories this issue falls and what to write in the description.

2022-01-10 14:06 UTC, Shnatsel requested changes
Thanks for the report! I've left a comment, looks good otherwise.

This seems to be a use-after-free, in case you want to categorize it further.

2022-01-10 14:06 UTC, Shnatsel commented on crates/dashmap/RUSTSEC-0000-0000.md
> +```
```suggestion
```unaffected = ["< 5.0.0"]
```

I've talked to the `dashmap` maintainer and they said that 4.x should be unaffected.

2022-01-10 18:49 UTC, baptiste0928 commented on crates/dashmap/RUSTSEC-0000-0000.md
> +```
I also tested on my side, only version `5.0.0` is affected.

2022-01-10 21:31 UTC, LeSeulArtichaut commented on crates/dashmap/RUSTSEC-0000-0000.md
> +Reference returned by `Ref::value` may outlive the `Ref` and escape the lock. This cause undefined behavior and may result in a segfault.
(Typo)
```suggestion
Reference returned by `Ref::value` may outlive the `Ref` and escape the lock. This causes undefined behavior and may result in a segfault.
```

2022-01-10 21:31 UTC, LeSeulArtichaut commented on crates/dashmap/RUSTSEC-0000-0000.md
> +categories = ["memory-corruption"]
Is there potential for memory exposure as well?

2022-01-12 05:09 UTC, ray-kast commented on crates/dashmap/RUSTSEC-0000-0000.md
> +Reference returned by `Ref::value` may outlive the `Ref` and escape the lock. This cause undefined behavior and may result in a segfault.
I believe in addition to `Ref::value` every method with a changed lifetime in [this PR](https://github.com/xacrimon/dashmap/pull/168/files) is affected by the same issue.

2022-01-12 05:11 UTC, ray-kast commented
(bump from a reply I accidentally added to a resolved conversation)
I believe in addition to `Ref::value` every method with a changed lifetime in [this PR](https://github.com/xacrimon/dashmap/pull/168/files) is affected by the same issue.

2022-01-13 16:28 UTC, merged

2022-01-13 16:28 UTC, Shnatsel commented
Merging. Thanks for the report and for the detailed advisory!