add advisory for cell-project
rustsec/advisory-db pull request #1391
Opened 2022-08-27 20:39 UTC by RustyYato

Fixes #1226

2022-08-27 20:43 UTC, pinkforest commented on crates/cell_project/RUSTSEC-0000-0000.md
> +informational = unsound
```suggestion
informational = "unsound"
```

2022-08-27 20:47 UTC, pinkforest commented on crates/cell_project/RUSTSEC-0000-0000.md
> +This was discovered and fixed by @Soni here: https://github.com/RustyYato/cell-project/issues/3 and https://github.com/RustyYato/cell-project/issues/4 respectively.
```suggestion
This was discovered and fixed by @SoniEx2 here in cell-project: [Issues/3] and [Issues/4] respectively.

[Issues/3]: https://github.com/RustyYato/cell-project/issues/3
[Issues/4]: https://github.com/RustyYato/cell-project/issues/4
```

2022-08-27 20:48 UTC, pinkforest commented on crates/cell_project/RUSTSEC-0000-0000.md
> +
```suggestion
references = ["https://github.com/RustyYato/cell-project/issues/3", "https://github.com/RustyYato/cell-project/issues/4"]

```

2022-08-27 20:51 UTC, pinkforest commented on crates/cell-project/RUSTSEC-0000-0000.md
> +macros = { "cell_project::cell_project" = ["< 0.1.4"], "nightly_cell_project" = ["< 0.1.4"] }
```suggestion
functions = { "cell_project::cell_project" = ["< 0.1.4"] }
```

Sadly we don't support macros atm sorry

2022-08-27 20:52 UTC, RustyYato commented on crates/cell-project/RUSTSEC-0000-0000.md
> +macros = { "cell_project::cell_project" = ["< 0.1.4"], "nightly_cell_project" = ["< 0.1.4"] }
☹️

2022-08-27 20:52 UTC, RustyYato commented on crates/cell-project/RUSTSEC-0000-0000.md
> +macros = { "cell_project::cell_project" = ["< 0.1.4"], "nightly_cell_project" = ["< 0.1.4"] }
Should I just label these as functions for the time being?

2022-08-27 20:52 UTC, pinkforest commented on crates/cell-project/RUSTSEC-0000-0000.md
> +affected = ["< 0.1.4"]
```suggestion
```

Can remove the affected, we only use unaffected in case there is unaffected range(s)

2022-08-27 20:54 UTC, pinkforest commented on crates/cell-project/RUSTSEC-0000-0000.md
> +macros = { "cell_project::cell_project" = ["< 0.1.4"], "nightly_cell_project" = ["< 0.1.4"] }
yah, sorry, we'll get better on that :) will mark this as something to catch-up on later

2022-08-27 20:58 UTC, pinkforest commented on crates/cell-project/RUSTSEC-0000-0000.md
> +
Was this example and the miri hosted somewhere? I was wondering if we could link there instead of in-lining here?

2022-08-27 21:00 UTC, pinkforest commented
Thanks a lot - Will merge tomorrow - just if we could link the example / miri output it would be great! :partying_face:

2022-08-27 21:00 UTC, RustyYato commented on crates/cell-project/RUSTSEC-0000-0000.md
> +
Not as far as I'm aware, (can't use playground for example because `cell-project` is too small). Is the concern that it takes up a lot of space visually? If so, I can put it in a summary block to hide it by default.

2022-08-27 21:05 UTC, RustyYato commented
Do you prefer if I squash all commits into one or is this fine as is?

2022-08-27 21:08 UTC, pinkforest commented
No need, we squash & merge always. Cheers

2022-08-27 21:17 UTC, pinkforest commented on crates/cell-project/RUSTSEC-0000-0000.md
> +
Just trying to keep advisories minimal and usually there is an issue in the repository that contains all the code examples or miri outputs - that's our usual way of doing it e.g. linking to the miri issue or PR would be sufficient perhaps.

2022-08-27 22:12 UTC, SoniEx2 requested changes

2022-08-27 22:12 UTC, SoniEx2 commented on crates/cell-project/RUSTSEC-0000-0000.md
> +        // NB: `Drop` is unsound.
`Drop` is unsound for self-referential types.

2022-08-27 22:17 UTC, pinkforest commented on crates/cell-project/RUSTSEC-0000-0000.md
> +        // NB: `Drop` is unsound.
@SoniEx2 Could we include this example (and the miri one) in the relevant cell-project Issue and then we can link there so we don't need to in-line here?

2022-08-27 22:19 UTC, SoniEx2 commented on crates/cell-project/RUSTSEC-0000-0000.md
> +        // NB: `Drop` is unsound.
@pinkforest isn't it literally copy-pasted from https://github.com/RustyYato/cell-project/issues/3#issue-1221798780 ?

2022-08-27 22:20 UTC, pinkforest commented on crates/cell-project/RUSTSEC-0000-0000.md
> +        // NB: `Drop` is unsound.
Yep correct, suggest to just link to that instead.

2022-08-27 22:21 UTC, pinkforest commented on crates/cell-project/RUSTSEC-0000-0000.md
> +
Hi @RustyYato 

@SoniEx2 just edited here: https://github.com/RustyYato/cell-project/issues/3#issue-1221798780

Can link the issue and the miri example there and we can save some database size here :) ty vm

2022-08-30 18:32 UTC, pinkforest commented
Thanks all :partying_face:  :purple_heart:

2022-08-30 18:32 UTC, merged