Add License CC-BY 4.0 Import exemption
rustsec/advisory-db pull request #1507
Opened 2023-01-06 16:50 UTC by pinkforest

Allows importing advisories with attribution from GHSA

EDIT: This is so that it will be ready for the tooling https://github.com/rustsec/rustsec/pull/682

2023-01-06 16:53 UTC, Shnatsel commented
I think we will need a more clear way to distinguish what data is under what license. For example a `license` field, or an explicitly specified attribution link since CC-BY requires attribution.

2023-01-06 16:54 UTC, pinkforest commented
Yes we cna do it after we have the license but that will require tooling changes.

In the meantime we can simply do a source attribution that seems to be the way nvd does it.

2023-01-06 16:54 UTC, Shnatsel commented
That is, I agree with the basic direction, but the implementation will be more complex than this.

FWIW I've already tried talking to Github about a licensing exception for RustSec and they said they aren't going to do it.

2023-01-06 16:55 UTC, pinkforest commented
Yeah I get the tooling is complex but having the license exemption approved & ready is a good start I would think ?

2023-01-06 16:55 UTC, Shnatsel commented
What I think could be valuable is a note that we're looking into adding advisories under CC-BY in the future, to ensure we can import from GHSA.

2023-01-06 16:57 UTC, pinkforest commented
But is that a license exemption issue that needs to be in license.txt ? This is just a legal foundational exemption blurb.

I've noted that importing which can generally by in CC-BY 4.0 term that is defined in the license.txt now

2023-01-06 17:01 UTC, pinkforest commented
For anyone ICYMI the tooling change PR is here: https://github.com/rustsec/rustsec/pull/682

2023-01-08 23:30 UTC, tarcieri approved these changes
This seems ok as a start, although it would be good to have a proper attribution for imported advisories with structured data about the license

2023-01-08 23:48 UTC, Shnatsel requested changes
The data up until now is exclusively public domain, and I think it's important to capture that.

Please rephrase this to state that CC-BY (or other) content may be added in the future, and that it only applies to licenses with attribution requirements but no additional clauses like copyleft.

2023-01-09 01:03 UTC, Shnatsel approved these changes

2023-01-09 01:46 UTC, alex commented on LICENSE.txt
> +copyleft.
I'm having a bit of trouble parsing this sentence. I think there might be a missing or extra word?

2023-01-09 02:37 UTC, pinkforest commented on LICENSE.txt
> +copyleft.
How about now?

2023-01-09 02:40 UTC, alex approved these changes

2023-01-09 16:49 UTC, amousset approved these changes

2023-01-09 16:55 UTC, amousset commented
This is a good first step, the next one is probably to reach a consensus on how to store this information in a structured way (in https://github.com/rustsec/rustsec/pull/682).

2023-01-09 16:57 UTC, merged