Update RUSTSEC-2021-0088.md
rustsec/advisory-db pull request #1512
Opened 2023-01-10 06:25 UTC by J3rry-1729

Patch has been made refer : https://github.com/jblondin/csv-sniffer/pull/2/

2023-01-12 22:34 UTC, pinkforest commented
It seems to read the patch was merged into 0.2 not 0.3 ? 
https://github.com/jblondin/csv-sniffer/pull/2#issuecomment-1073049946

Also please can we add `references = ["url"] `and leave url as is pointing to the issue

2023-01-12 22:37 UTC, pinkforest commented on crates/csv-sniffer/RUSTSEC-2021-0088.md
> +url = "https://github.com/jblondin/csv-sniffer/pull/2"
```suggestion
references = ["https://github.com/jblondin/csv-sniffer/pull/2"]
```
Can only have one url that points to the origin issue and then references can be used to describe the fix.

2023-01-14 01:00 UTC, pinkforest commented on crates/csv-sniffer/RUSTSEC-2021-0088.md
> +patched = [">= 0.3.0"]
```suggestion
patched = [">= 0.2.0"]
```
I think this may have been fixed in 0.2 - checking here with the maintainer https://github.com/jblondin/csv-sniffer/pull/2#issuecomment-1382616068

2023-01-14 01:01 UTC, pinkforest requested changes
Just checking the version here first per comment

2023-01-14 01:01 UTC, pinkforest commented on crates/csv-sniffer/RUSTSEC-2021-0088.md
> +patched = [">= 0.3.0"]
```suggestion
patched = [">= 0.2.0"]
```
I think this may have been fixed in 0.2 - checking here with the maintainer https://github.com/jblondin/csv-sniffer/pull/2#issuecomment-1382616068

2023-01-15 08:06 UTC, J3rry-1729 commented
Yep the fix is 0.2 changed the PR as requested

2023-01-15 08:13 UTC, pinkforest approved these changes

2023-01-15 08:14 UTC, merged