Add unmaintained advisory for safemem
rustsec/advisory-db pull request #1615
Opened 2023-02-20 11:54 UTC by oherrala

safemem is crate by @abonander who has archived bunch of his Rust crates in GitHub.

2023-04-06 10:52 UTC, pinkforest requested changes
Please can we use formatting / fill the necessary detail accordingly per this example:
https://github.com/rustsec/advisory-db/blob/main/crates/buf_redux/RUSTSEC-2023-0028.md

2023-04-06 14:26 UTC, dignifiedquire commented
> I wonder if `buffer-redux` could possibly adopt a fork of this as well .. or drop / switch it by any chance ?

Probably makes sense to either inline or replace.

2024-02-22 20:33 UTC, oherrala commented
The `safemem` GitHub repository has been archived: https://github.com/abonander/safemem

>  This repository has been archived by the owner on Feb 14, 2023. It is now read-only.

2024-02-22 20:42 UTC, Shnatsel commented
Thanks for the heads-up!

I've changed the advisory to only include very obviously correct and uncontroversial statements. I'm going to go ahead and merge this now that we have a clear signal from the maintainer in the form of an archived repo.

2024-02-22 20:42 UTC, merged

2024-03-04 18:06 UTC, Skgland commented
The safemem crate only has three functions, two of which have standard library alternatives by now and one can be workedaround relatively easily. Would it make sense to include some migration instructions in the form of:

### Migration

- `safemem::copy_over(slice, src_idx, dest_idx, len);` can be replaced with `slice.copy_within(src_idx..src_idx+len, dest_idx);`
- `safemem::write_bytes(slice, byte);` can be replaced with `slice.fill(byte);`
- `safemem::prepend(slice, vec);` can be replaced with 
  ```rust
  let old_len = vec.len();
  vec.extend_from_slice(slice);
  vec.rotate_left(old_len);
  ```

2024-03-04 18:24 UTC, amousset commented
Sure :+1:, feel free to open a PR.