Add advisory for sequoia-openpgp
rustsec/advisory-db pull request #1696
Opened 2023-05-19 18:27 UTC by nwalfield

Attacker-controlled input can lead to an out-of-bounds index, which causes sequoia-openpgp to panic.  This has been fixed in versions 1.16.0, 1.8.1, and 1.1.1 of sequoia-openpgp.

2023-05-28 14:37 UTC, amousset requested changes

2023-05-28 14:37 UTC, amousset commented on crates/sequoia-openpgp/RUSTSEC-0000-0000.md
> +```
```suggestion
```

2023-05-28 14:37 UTC, amousset commented on crates/sequoia-openpgp/RUSTSEC-0000-0000.md
> +unaffected = ["1.1.1", "1.8.1"]
`unaffected` is for versions that were never affected (usually versions before the vulnerability was introduced).

If I understand correctly it should not be used here as all versions of the crate were affected.

2023-05-28 14:37 UTC, amousset commented on crates/sequoia-openpgp/RUSTSEC-0000-0000.md
> +patched = [">= 1.16.0"]
```suggestion
patched = [">= 1.1.1, < 1.2.0", ">= 1.8.1, < 1.9.0", ">= 1.16.0"]
```

2023-05-31 08:44 UTC, nwalfield commented on crates/sequoia-openpgp/RUSTSEC-0000-0000.md
> +```
Good catch, thanks

2023-05-31 08:44 UTC, nwalfield commented on crates/sequoia-openpgp/RUSTSEC-0000-0000.md
> +unaffected = ["1.1.1", "1.8.1"]
Thanks for the explanation.

2023-05-31 08:45 UTC, nwalfield commented on crates/sequoia-openpgp/RUSTSEC-0000-0000.md
> +patched = [">= 1.16.0"]
Thanks for the suggestion, I've add it.

2023-05-31 20:51 UTC, amousset approved these changes

2023-05-31 20:54 UTC, merged

2023-05-31 20:55 UTC, amousset commented
Thanks for your report!