blurhash-rs panic-on-parse
rustsec/advisory-db pull request #1786
Opened 2023-09-19 11:36 UTC by rubdos

https://github.com/whisperfish/blurhash-rs/security/advisories/GHSA-cxvp-82cq-57h2

2023-12-12 20:03 UTC, SteinHeselmans approved these changes

2024-03-02 02:53 UTC, Shnatsel requested changes

2024-03-02 02:53 UTC, Shnatsel commented on crates/blurhash/RUSTSEC-0000-0000.md
> +The patches will be released under version 0.2.0, which may require user intervention because of slight API churn.
The patch is out now, so could you update the language to indicate that?

Other than that looks good. Thanks!

2024-03-02 12:22 UTC, rubdos commented on crates/blurhash/RUSTSEC-0000-0000.md
> +The patches will be released under version 0.2.0, which may require user intervention because of slight API churn.
Done, thanks!

2024-03-02 17:21 UTC, Shnatsel approved these changes

2024-03-02 17:21 UTC, merged