Add notices for `trust-dns`
rustsec/advisory-db pull request #1806
Opened 2023-10-18 02:04 UTC by thomaseizinger

Resolves: #1804.

2023-10-18 03:38 UTC, bluejekyll commented
I'm not sure I agree completely with this. We're discussing in the hickory-dns repos (formerly trust-dns), I'd like to come to a consensus there before publishing an advisory like this.

2023-10-18 20:49 UTC, bluejekyll requested changes
I'm still not sure we want to publish this, but it's missing a note on `trust-dns-util` as well, which is now `hickory-util`

Also, maybe add this issue as a reference? https://github.com/hickory-dns/hickory-dns/issues/2051

```toml
references = ["https://github.com/hickory-dns/hickory-dns/issues/2051"]
```

2023-10-19 03:43 UTC, thomaseizinger commented
> Also, maybe add this issue as a reference? [hickory-dns/hickory-dns#2051](https://github.com/hickory-dns/hickory-dns/issues/2051)

I'll add it once there is consensus that these will be published :)

2023-10-23 16:01 UTC, bluejekyll requested changes

2023-10-23 16:01 UTC, bluejekyll commented on crates/trust-dns-client/RUSTSEC-0000-0000.md
> +unaffected = ["< 0.23.0"]
Should this be `<= 0.23.0` or `< 0.23.1`? I'm assuming `<` in this context is exclusive, not inclusive. (at least in our discussion I thought we had agreed that only everything after `0.23.0` would be considered unmaintained, which are currently `0.23.1` and `0.23.2`).

2023-10-23 16:03 UTC, djc commented on crates/trust-dns-client/RUSTSEC-0000-0000.md
> +unaffected = ["< 0.23.0"]
I was wondering the same thing.

2023-10-23 20:25 UTC, thomaseizinger commented on crates/trust-dns-client/RUSTSEC-0000-0000.md
> +unaffected = ["< 0.23.0"]
Ah yeah, my bad. I changed it several times because I got confused by the negation of affected/unaffected and the resulting semver bounds.

2023-10-24 16:34 UTC, bluejekyll commented on crates/trust-dns-client/RUSTSEC-0000-0000.md
> +unaffected = ["< 0.23.0"]
oh, also, I think we're still missing an advisory for `trust-dns-util`

2023-10-25 18:45 UTC, bluejekyll approved these changes
This looks good to me, and I agree with the filing. Thank you for working with us at the project to come to a decent resolution on this @thomaseizinger, I really appreciate your time and effort on this.

2023-10-25 21:15 UTC, thomaseizinger commented
> This looks good to me, and I agree with the filing. Thank you for working with us at the project to come to a decent resolution on this @thomaseizinger, I really appreciate your time and effort on this.

You are welcome, thank you for collaborating on it! :)

2023-12-06 19:30 UTC, pinkforest commented
Multi-crate projects have been typically dealt by adding an advisory around a root crate lightning up all downstream.

It seems `trust-dns-proto` is dependency of `trust-dns-server,` `trust-dns-client`, `trust-dns-resolver`, `trust-dns`

For precedent see. [git/gix rename](https://github.com/rustsec/advisory-db/blob/main/crates/git-path/RUSTSEC-2023-0026.md) via [PR/1644](https://github.com/rustsec/advisory-db/pull/1644) and [rusoto](https://github.com/rustsec/advisory-db/blob/main/crates/rusoto_credential/RUSTSEC-2022-0071.md) via [PR/1494](https://github.com/rustsec/advisory-db/pull/1494)

2023-12-06 21:42 UTC, thomaseizinger commented
I don't mind either way, happy to remove all but `trust-dns-proto`!

2024-12-04 12:43 UTC, kornelski approved these changes

2024-12-04 12:45 UTC, djc commented
> I don't mind either way, happy to remove all but `trust-dns-proto`!

I think that would make sense.

Probably makes sense to move this forward at this point?

2024-12-04 12:46 UTC, kornelski commented
I think it's okay to merge as-is. It has version limit as requested by upstream, and these crates haven't been touched for a year now, so they really are unmaintained.

2024-12-20 10:27 UTC, djc commented
Maintainers (@Shnatsel?), how can we move this forward? I'd like to get it released.

2025-03-22 11:53 UTC, djc commented
@thomaseizinger I'm a maintainer now -- would you be willing to squash this down to a single advisory for trust-dns-proto only, dated today/some time recent? Then I can get this merged.

2025-03-22 12:40 UTC, thomaseizinger commented
> @thomaseizinger I'm a maintainer now -- would you be willing to squash this down to a single advisory for trust-dns-proto only, dated today/some time recent? Then I can get this merged.

Yep, can do tomorrow! `trust-dns-proto` is the root crate I guess? So that will generate a notice for everyone?

2025-03-22 12:44 UTC, djc commented
> > @thomaseizinger I'm a maintainer now -- would you be willing to squash this down to a single advisory for trust-dns-proto only, dated today/some time recent? Then I can get this merged.
> 
> 
> 
> Yep, can do tomorrow! `trust-dns-proto` is the root crate I guess? So that will generate a notice for everyone?

Yes, that's the idea.

2025-03-23 05:03 UTC, thomaseizinger commented
@djc Done!

2025-03-23 06:02 UTC, djc approved these changes

2025-03-23 06:02 UTC, merged

2025-03-23 06:02 UTC, djc commented
Thanks!