Add advisory for memory leak in ic-stable-structures
rustsec/advisory-db pull request #1969
Opened 2024-05-21 09:55 UTC by venkkatesh-sekar

2024-05-23 09:32 UTC, venkkatesh-sekar commented
Hi @Shnatsel, can you please have a look?

2024-05-30 17:51 UTC, riking requested changes

2024-05-30 17:51 UTC, riking commented on crates/ic-stable-structures/RUSTSEC-0000-0000.md
> +categories = ["memory-corruption"]
The correct category is `denial-of-service`, nothing in the advisory text you've written suggests memory corruption?

2024-05-30 17:51 UTC, riking commented on crates/ic-stable-structures/RUSTSEC-0000-0000.md
> +keywords = ["canister", "icp", "stable memory"]
maybe keyword "memory leak"?

2024-05-30 17:51 UTC, riking commented on crates/ic-stable-structures/RUSTSEC-0000-0000.md
> +date = "2023-05-21"
Date is 2024-05-17

2024-05-30 18:04 UTC, venkkatesh-sekar commented on crates/ic-stable-structures/RUSTSEC-0000-0000.md
> +categories = ["memory-corruption"]
Yeah, denial-of-service fits better.

2024-06-03 14:20 UTC, venkkatesh-sekar commented
Hey @Shnatsel, friendly ping. Happy to discuss if something is blocking this.

2024-12-04 12:40 UTC, kornelski approved these changes

2024-12-04 12:42 UTC, merged