Add unmaintained advisories
rustsec/advisory-db pull request #2079
Opened 2024-09-14 23:30 UTC by bircni

Closes #2078

2024-09-14 23:49 UTC, GnomedDev requested changes
If you could also add my `typesize` library to the alternatives list, that would be great.

2024-09-14 23:49 UTC, GnomedDev commented on crates/get-size-derive/RUSTSEC-0000-0000.md
> +- [proc-macro-error2](https://crates.io/crates/get-size-derive2)
You forgot to change the text to `get-size-derive2`.

2024-09-14 23:49 UTC, GnomedDev commented on crates/get-size/RUSTSEC-0000-0000.md
> +- [proc-macro-error2](https://crates.io/crates/get-size2)
Ditto

2024-09-15 11:08 UTC, bircni commented on crates/get-size-derive/RUSTSEC-0000-0000.md
> +- [proc-macro-error2](https://crates.io/crates/get-size-derive2)
oops maybe it was a bit too late xD

2024-09-16 15:38 UTC, GnomedDev approved these changes
Advisories look good to me, although I think this will take a bit to wait to give them a chance to respond to the issue.

2024-12-04 12:22 UTC, kornelski approved these changes

2024-12-05 16:42 UTC, bircni commented
@amousset is this ok to merge?

2024-12-07 19:35 UTC, kornelski approved these changes

2024-12-20 21:01 UTC, bircni commented
90 days are over and I still got no response - I think now we can merge

2024-12-22 09:00 UTC, merged